export const MODE_CREATE_CAMPAIGN_PART_A_FLAG = 0x00
export const MODE_CREATE_CAMPAIGN_PART_B_FLAG = 0x01
export const MODE_FUND_CAMPAIGN_FLAG = 0x02
export const MODE_VOTE_REJECT_FLAG = 0x03
export const MODE_VOTE_APPROVE_FLAG = 0x04
export const MODE_REQUEST_REFUND_PAYMENT_FLAG = 0x05
export const MODE_REQUEST_MILESTONE_PAYOUT_PAYMENT_FLAG = 0x06
